version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rainbow
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    
    ports:
      - '5050:80'

    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin-data: